item { 
	name:'zero'
	id:1
}
item { 
	name:'one'
	id:2
}
item { 
	name:'two'
	id:3
}
item { 
	name:'three'
	id:4
}
item { 
	name:'four'
	id:5
}
item { 
	name:'five'
	id:6
}
item { 
	name:'six'
	id:7
}
item { 
	name:'seven'
	id:8
}
item { 
	name:'eight'
	id:9
}
item { 
	name:'nine'
	id:10
}
item { 
	name:'time'
	id:11
}
item { 
	name:'north'
	id:12
}
item { 
	name:'south'
	id:13
}
item { 
	name:'counting'
	id:14
}
